[package]
name = "default-config"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
jay-config = { path = "../jay-config" }
log = "0.4.14"
rand = "0.8.5"
chrono = "0.4.19"
battery = "0.7.8"
uom = "0.30.0"
sysinfo = "*"
